# Generated by Django 5.1.2 on 2024-11-07 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0002_profile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
