# Generated by Django 5.1.6 on 2025-02-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_availability_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='availability',
        ),
        migrations.AddField(
            model_name='resort',
            name='events',
            field=models.ManyToManyField(related_name='resorts', to='events.event'),
        ),
    ]
