# Generated by Django 5.1.6 on 2025-02-20 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_produto_remove_resort_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.resort'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='resorts', to='events.event'),
        ),
    ]
