# Generated by Django 5.1.6 on 2025-02-20 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_resort_alter_resort_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='events.team'),
        ),
    ]
