# Generated by Django 5.1.6 on 2025-02-20 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_availability_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='events.team'),
        ),
    ]
