# Generated by Django 5.1.2 on 2024-10-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_agency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='key_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
