# Generated by Django 5.1.2 on 2024-10-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoria', '0003_bankaccount_account_agency_bankaccount_key_pix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='Documents_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='Documents_type',
        ),
        migrations.AddField(
            model_name='document',
            name='cnpj_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='cpf_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pis_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rg_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='work_regime',
            field=models.CharField(choices=[('regime_clt', 'Regime CLT'), ('regime_pj', 'Regime PJ')], default='regime_clt', max_length=10),
        ),
    ]
