# Generated by Django 5.1.2 on 2024-11-03 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoria', '0008_remove_event_teams_event_daily_event_end_date_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='cancellation',
        ),
        migrations.AddField(
            model_name='availability',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='monitoria.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='max_availabilities',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='daily',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='monitoria.event'),
        ),
    ]
