# Generated by Django 5.1.2 on 2024-11-03 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoria', '0011_availability_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='monitoria.availability'),
        ),
    ]
