# Generated by Django 5.1.2 on 2024-11-05 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('monitoria', '0012_cancellation_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='cancellation',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='team',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='event',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='event',
            name='resort',
        ),
        migrations.AlterField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='events',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.DeleteModel(
            name='Cancellation',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Resort',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
