# Generated by Django 5.1.2 on 2024-11-07 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoria', '0015_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='profile',
        ),
    ]
