from django.urls import path
from .views import (
    PaymentDetailView,
    PaymentListView,
    PaymentStatusUpdateView,
    RatingCreateView,
    RatingListView,
    RatingUpdateView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    DocumentListView,
    DocumentCreateView,
    DocumentDetailView,
    DocumentUpdateView,
    BankAccountListView,
    BankAccountCreateView,
    BankAccountDetailView,
    BankAccountUpdateView,
    UniformListView,
    UniformCreateView,
    UniformDetailView,
    UniformUpdateView,
    AddressListView,
    AddressCreateView,
    AddressDetailView,
    AddressUpdateView,
    teste,
)

app_name = "monitoria"

urlpatterns = [
    path("teste/", teste, name="teste"),
    path("payments/", PaymentListView.as_view(), name="payment_list"),
    path("payments/<int:pk>/", PaymentDetailView.as_view(), name="payment_detail"),
    path(
        "payments/<int:pk>/status/",
        PaymentStatusUpdateView.as_view(),
        name="payment_status_update",
    ),
    path("ratings/", RatingListView.as_view(), name="rating_list"),
    path("ratings/new/", RatingCreateView.as_view(), name="rating_create"),
    path("ratings/<int:pk>/edit/", RatingUpdateView.as_view(), name="rating_edit"),
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("categories/new/", CategoryCreateView.as_view(), name="category_create"),
    path("categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category_edit"),
    path("documents/", DocumentListView.as_view(), name="document_list"),
    path("documents/new/", DocumentCreateView.as_view(), name="document_create"),
    path("documents/<int:pk>/", DocumentDetailView.as_view(), name="document_detail"),
    path("documents/<int:pk>/edit/", DocumentUpdateView.as_view(), name="document_edit"),
    path("bankaccounts/", BankAccountListView.as_view(), name="bankaccount_list"),
    path("bankaccounts/new/", BankAccountCreateView.as_view(), name="bankaccount_create"),
    path("bankaccounts/<int:pk>/", BankAccountDetailView.as_view(), name="bankaccount_detail"),
    path("bankaccounts/<int:pk>/edit/", BankAccountUpdateView.as_view(), name="bankaccount_edit"),
    path("uniforms/", UniformListView.as_view(), name="uniform_list"),
    path("uniforms/new/", UniformCreateView.as_view(), name="uniform_create"),
    path("uniforms/<int:pk>/", UniformDetailView.as_view(), name="uniform_detail"),
    path("uniforms/<int:pk>/edit/", UniformUpdateView.as_view(), name="uniform_edit"),
    path("addresses/", AddressListView.as_view(), name="address_list"),
    path("addresses/new/", AddressCreateView.as_view(), name="address_create"),
    path("addresses/<int:pk>/", AddressDetailView.as_view(), name="address_detail"),
    path("addresses/<int:pk>/edit/", AddressUpdateView.as_view(), name="address_edit"),
]
